### PR TITLE
Make `waitFor` interceptable and don't override interval/timeout

### PR DESCRIPTION
**Pull request by ghengeveld**
Works in tandem with https://github.com/storybookjs/storybook/pull/18460

## Change Type

Indicate the type of change your pull request is:

- [ ] `maintenance`
- [ ] `documentation`
- [x] `patch`
- [ ] `minor`
- [ ] `major`

<details>
  <summary>📦 Published PR as canary version: <code>0.0.14--canary.23.51ebb1b.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @storybook/testing-library@0.0.14--canary.23.51ebb1b.0
  # or 
  yarn add @storybook/testing-library@0.0.14--canary.23.51ebb1b.0
  ```
</details>

### CODE REVIEW

**Review by yannbf — APPROVED** [review]
Great stuff @ghengeveld ! What does this mean for users that might be in a scenario with Storybook 6.4 and the new version of this package?

**Comment by yannbf** [comment]
Nevermind I got the answer. 

For situations where steps pass, it will surface waitFor:

image

--- 
But in a failure scenario, there is a big difference:

**Before:**
image

**After:**
image

**Comment by IanVS** [comment]
Is it possible that this will fix https://github.com/storybookjs/testing-library/issues/9?  And maybe even https://github.com/storybookjs/testing-library/issues/8, or is that too optimistic of me?

**Comment by ghengeveld** [comment]
> Is it possible that this will fix #9? And maybe even #8, or is that too optimistic of me?

There's a good chance this will address #9 because we've gotten rid of "forwardedExceptions" which sometimes led to weird behavior. Give it a try!

At the very least this will log any exception before throwing the `ignoredException`, so you'll be able to see the original error in the browser console. I'll also revisit https://github.com/storybookjs/storybook/pull/16592 which is related.

**Comment by IanVS** [comment]
Hi, I'm excited for this change, is it waiting for something, or maybe it can be merged?

**Comment by yannbf** [comment]
> Hi, I'm excited for this change, is it waiting for something, or maybe it can be merged?

It's complicated. This fix is tied to a fix that currently only lives in storybook 7. If this change was merged, it'd bring a regression for 6.5 users (as I mentioned above). What I'm hoping for is to patch the interaction fix back to Storybook 6.5, and then everything would become much simpler (though could still impact 6.4 users). Cc @shilman 

We're currently using the alpha in the storybook monorepo :s

**Comment by IanVS** [comment]
As we approach 7.0 beta, whats the plan for this PR?

**Pull request merged**
